apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: adf-batch-job-demo-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: adf-batch-job-demo-job
spec:
  jobTargetRef:
    parallelism: 1 
    completions: 1 
    template:
      metadata:
        labels:
          app: adf-batch-job-demo-job
          aadpodidbinding: {{ .Values.pod_identity.binding }}
      spec:
        containers:
        - name: adf-batch-job-demo-job
          image: {{ print .Values.image.repository ":" .Values.image.version  }}
          env:
            - name: SERVICE_BUS
              value: {{ .Values.service_bus.namespace }}
            - name: QUEUE_NAME
              value: {{ .Values.service_bus.queue_name }}
            - name: MSI_CLIENT_ID
              value: {{ .Values.pod_identity.client_id }}
        restartPolicy: Never
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: {{ .Values.service_bus.queue_name }}
      namespace: {{ .Values.service_bus.namespace }}
      messageCount: "2"
    authenticationRef:
        name: adf-batch-job-demo-auth 